product:
  service:
    url: http://localhost:8080/api/v1/products

server:
  port: 8081
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

integration:
  client:
    url: http://localhost:8080/api/v1/products/{productId}
    connectionTimeout: 5s
    readTimeout: 5s
