spring:
  liquibase:
    url: jdbc:postgresql://localhost:5433/postgres
    user: postgres
    password: postgres
    change-log: classpath:changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
application:
  mainDatasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    maxPoolSize: 5

